### ISSUE TITLE
Strip EXIF metadata from uploaded images

### ISSUE THREAD

**Issue by duijf** [svsticky/pxl#13]
Stuff like exact date/time, location and a bunch of other things. We don't need it for anything, so we shouldn't store it.

**Comment by tomwassenberg** [comment]
Maybe leave the date/time, because we might want to use it for sorting within albums?

**Comment by duijf** [comment]
The PIL library that we use apparently does this already according to [this SO answer](https://stackoverflow.com/a/51213844) @HugoPeters1024 found, so if we want to save _some_ data, we would have to program this explicitly.

**Comment by maartenberg** [comment]
We'll also want to preserve the Rotation tag, since an image can get messed up otherwise (build and see http://localhost:8000/2018-05-13-fissabon/ for an example, this image shows correctly in the source file).

**Comment by duijf** [comment]
Instead of preserving `Orientation`, we'll just read it from the image and rotate/flip the image accordingly.
