### ISSUE TITLE
Not all album thumbnails are displayed in Firefox

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/pxl#48]
In Firefox, on 100% zoom, not all album thumbnails are shown on the homepage. On my resolution (2560x1440), I see 25, which increases when zooming out.

On Chrome all thumbnails are all shown. (Although some rows are of a different size.)

**Comment by maartenberg** [comment]
Fixed by 84b9fc628fec4716be464be70996adae2e471f27.
