### ISSUE TITLE
Bottom shadow is missing a line of pixels

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/pxl#73]
The shadow for the album title doesn't go down entirely. This causes an ugly line under each album with the original color. See the image below for an example.
![image](https://user-images.githubusercontent.com/16525696/74103367-d0723f00-4b4b-11ea-947f-8337c76b6391.png)

**Comment by maartenberg** [comment]
What device/browser is this happening on? I don't see this on Firefox 72 on Linux:

![2020-02-14T12:24:15+01:00](https://user-images.githubusercontent.com/8876997/74527019-fe2cfe80-4f24-11ea-85b2-eb553bd47afe.png)

**Comment by Mstiekema** [comment]
I see this on Windows Firefox 72. It starts to show starting from the third row of albums.
