### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/pxl#8]

**Comment by duijf** [comment]
Good point. I've opened #16 for this (and some docs about the philosphy). I went with the MPL as a simple, not too restrictive copyleft license. We can discuss the license here.

Any opinions, @tomwassenberg, @HugoPeters1024, @arianvp?

**Comment by HugoPeters1024** [comment]
Is GNU only a meme? Cause it's sounds alright on paper if you ask me.

Op di 6 nov. 2018 22:14 schreef Laurens Duijvesteijn <
notifications@github.com:

**Comment by arianvp** [comment]
No gnu is not a meme.

**Comment by duijf** [comment]
I'm not married to anything. Here's a comparison: https://choosealicense.com/licenses/

Also good to read: https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

**Comment by arianvp** [comment]
MPL is fine

**Comment by duijf** [comment]
So MPL it is?

**Comment by duijf** [comment]
Fixed in https://github.com/svsticky/pxl/commit/4084a077ce568ea7bc7e1683b7e66d2f57c7c5f6
